In [1]:
import pandas as pd

In [2]:
people={
    'first':['harry','ram','shyam','pandav'],
    'last':['patil','pawar','bhosale','jadhav'],
    'email':['uvw@gmail.com','xyz@gmail.com','pqr@gmail.com','abcgmail.com'],
}

In [3]:
df=pd.DataFrame(people)

In [4]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [5]:
filt=df['first']=='shyam'

In [6]:
filt

0    False
1    False
2     True
3    False
Name: first, dtype: bool

In [7]:
df[filt]

   first     last          email
2  shyam  bhosale  pqr@gmail.com

In [9]:
df.loc[filt,'email']

2    pqr@gmail.com
Name: email, dtype: object

In [11]:
df.loc[filt,['email','first']]

           email  first
2  pqr@gmail.com  shyam

In [13]:
df.loc[-filt,'first']

0     harry
1       ram
3    pandav
Name: first, dtype: object