In [1]:
import pandas as pd

In [7]:
data={
    'letter':['A','B','C','D','E','F','G','H'],
    'code':[1,2,3,4,5,6,7,8]
}

In [8]:
df=pd.DataFrame(data)

In [9]:
df

  letter  code
0      A     1
1      B     2
2      C     3
3      D     4
4      E     5
5      F     6
6      G     7
7      H     8

In [10]:
df.sort_values(by='letter',ascending=False)

  letter  code
7      H     8
6      G     7
5      F     6
4      E     5
3      D     4
2      C     3
1      B     2
0      A     1

In [12]:
df.sort_values(by='code',ascending=True)

  letter  code
0      A     1
1      B     2
2      C     3
3      D     4
4      E     5
5      F     6
6      G     7
7      H     8

In [13]:
df.sort_values(by=['letter','code'],ascending=[True,False])

  letter  code
0      A     1
1      B     2
2      C     3
3      D     4
4      E     5
5      F     6
6      G     7
7      H     8

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  8 non-null      object
 1   code    8 non-null      int64
dtypes: int64(1), object(1)
memory usage: 260.0+ bytes

In [16]:
df.nlargest(1,'code')

  letter  code
7      H     8

In [19]:
df['letter']=df['letter'].astype('string')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  8 non-null      string
 1   code    8 non-null      int64
dtypes: int64(1), string(1)
memory usage: 260.0 bytes

In [24]:
df.nsmallest(1,'code')

  letter  code
0      A     1