In [2]:
import pandas as pd

In [3]:
people={
    'first':['harry','ram','shyam','pandav'],
    'last':['patil','pawar','bhosale','jadhav'],
    'email':['uvw@gmail.com','xyz@gmail.com','pqr@gmail.com','abcgmail.com'],
}

In [4]:
df=pd.DataFrame(people)

In [5]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [10]:
df['full']=df['first']+' '+df['last']

In [7]:
df

    first     last          email           full
0   harry    patil  uvw@gmail.com    harry patil
1     ram    pawar  xyz@gmail.com      ram pawar
2   shyam  bhosale  pqr@gmail.com  shyam bhosale
3  pandav   jadhav   abcgmail.com  pandav jadhav

In [8]:
df.drop(columns=['full'],inplace=True)

In [9]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [11]:
df

    first     last          email           full
0   harry    patil  uvw@gmail.com    harry patil
1     ram    pawar  xyz@gmail.com      ram pawar
2   shyam  bhosale  pqr@gmail.com  shyam bhosale
3  pandav   jadhav   abcgmail.com  pandav jadhav

In [13]:
df['full'].str.split(' ')

0      [harry, patil]
1        [ram, pawar]
2    [shyam, bhosale]
3    [pandav, jadhav]
Name: full, dtype: object

In [19]:
df['full']=df['full'].str.split(' ',expand=True)[0].str.title()+' '+df['full'].str.split(' ',expand=True)[1].str.title()

In [20]:
df

    first     last          email           full
0   harry    patil  uvw@gmail.com    Harry Patil
1     ram    pawar  xyz@gmail.com      Ram Pawar
2   shyam  bhosale  pqr@gmail.com  Shyam Bhosale
3  pandav   jadhav   abcgmail.com  Pandav Jadhav

In [22]:
df[['first','last']]=df['full'].str.split(' ',expand=True)

In [23]:
df

    first     last          email           full
0   Harry    Patil  uvw@gmail.com    Harry Patil
1     Ram    Pawar  xyz@gmail.com      Ram Pawar
2   Shyam  Bhosale  pqr@gmail.com  Shyam Bhosale
3  Pandav   Jadhav   abcgmail.com  Pandav Jadhav

In [24]:
df.append({'first':'Raju','last':'Patil','email':'pqr@gmail.com','full':'Raju Patil'}) #removed from pandas

AttributeError: 'DataFrame' object has no attribute 'append'

In [25]:
new_row={'first':'Raju','last':'Patil','email':'pqr@gmail.com','full':'Raju Patil'}

In [27]:
df_new_row=pd.DataFrame([new_row])

In [28]:
df_new_row

  first   last          email        full
0  Raju  Patil  pqr@gmail.com  Raju Patil

In [33]:
df=pd.concat([df,df_new_row],ignore_index=True)

In [34]:
df

    first     last          email           full
0   Harry    Patil  uvw@gmail.com    Harry Patil
1     Ram    Pawar  xyz@gmail.com      Ram Pawar
2   Shyam  Bhosale  pqr@gmail.com  Shyam Bhosale
3  Pandav   Jadhav   abcgmail.com  Pandav Jadhav
4    Raju    Patil  pqr@gmail.com     Raju Patil
5    Raju    Patil  pqr@gmail.com     Raju Patil

In [37]:
df.drop(index=[5],inplace=True)

In [38]:
df

    first     last          email           full
0   Harry    Patil  uvw@gmail.com    Harry Patil
1     Ram    Pawar  xyz@gmail.com      Ram Pawar
2   Shyam  Bhosale  pqr@gmail.com  Shyam Bhosale
3  Pandav   Jadhav   abcgmail.com  Pandav Jadhav
4    Raju    Patil  pqr@gmail.com     Raju Patil