In [1]:
import pandas as pd

In [2]:
people={
    'first':['harry','ram','shyam','pandav'],
    'last':['patil','pawar','bhosale','jadhav'],
    'email':['uvw@gmail.com','xyz@gmail.com','pqr@gmail.com','abcgmail.com'],
}

In [3]:
df=pd.DataFrame(people)

In [4]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [5]:
df['first']

0     harry
1       ram
2     shyam
3    pandav
Name: first, dtype: object

In [6]:
type(df['first'])

pandas.core.series.Series

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.email

0    uvw@gmail.com
1    xyz@gmail.com
2    pqr@gmail.com
3     abcgmail.com
Name: email, dtype: object

In [9]:
df[['first','email']]

    first          email
0   harry  uvw@gmail.com
1     ram  xyz@gmail.com
2   shyam  pqr@gmail.com
3  pandav   abcgmail.com

In [11]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [12]:
df.iloc[0]

first            harry
last             patil
email    uvw@gmail.com
Name: 0, dtype: object

In [14]:
df.iloc[[0,2]]

   first     last          email
0  harry    patil  uvw@gmail.com
2  shyam  bhosale  pqr@gmail.com

In [ ]:
# df.iloc[[0,2],'last']  not allowed here but use only index only

In [16]:
df.iloc[[0,2],1]

0      patil
2    bhosale
Name: last, dtype: object

In [17]:
df.iloc[[0,2],[1,2]]

      last          email
0    patil  uvw@gmail.com
2  bhosale  pqr@gmail.com

In [18]:
df.loc[[0,1]]

   first   last          email
0  harry  patil  uvw@gmail.com
1    ram  pawar  xyz@gmail.com

In [21]:
df.loc[[0,1],['first','email']]

   first          email
0  harry  uvw@gmail.com
1    ram  xyz@gmail.com

In [22]:
df.loc[0,'first']

'harry'

In [24]:
df['hobby']=['yes','no','yes','yes']

In [25]:
df

    first     last          email hobby
0   harry    patil  uvw@gmail.com   yes
1     ram    pawar  xyz@gmail.com    no
2   shyam  bhosale  pqr@gmail.com   yes
3  pandav   jadhav   abcgmail.com   yes

In [26]:
df['hobby'].value_counts()

hobby
yes    3
no     1
Name: count, dtype: int64

In [27]:
df.loc[0:2,'hobby']

0    yes
1     no
2    yes
Name: hobby, dtype: object

In [29]:
df.loc[0:2,'last':'hobby']

      last          email hobby
0    patil  uvw@gmail.com   yes
1    pawar  xyz@gmail.com    no
2  bhosale  pqr@gmail.com   yes