In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.0'

In [3]:
people={
    'first':['harry','ram','shyam','pandav'],
    'last':['patil','pawar','bhosale','jadhav'],
    'email':['uvw@gmail.com','xyz@gmail.com','pqr@gmail.com','abcgmail.com'],
}

In [4]:
df=pd.DataFrame(people)

In [5]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [7]:
df.columns=[x.upper() for x in df.columns]

In [8]:
df

    FIRST     LAST          EMAIL
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [9]:
df.columns=['first_name','last_name','email']

In [10]:
df

  first_name last_name          email
0      harry     patil  uvw@gmail.com
1        ram     pawar  xyz@gmail.com
2      shyam   bhosale  pqr@gmail.com
3     pandav    jadhav   abcgmail.com

In [11]:
df.columns=df.columns.str.replace('_'," ")
df

  first name last name          email
0      harry     patil  uvw@gmail.com
1        ram     pawar  xyz@gmail.com
2      shyam   bhosale  pqr@gmail.com
3     pandav    jadhav   abcgmail.com

In [12]:
df.columns=['first','last','email']

In [13]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [15]:
df['full']=df['first']+' '+df['last']

In [16]:
df

    first     last          email           full
0   harry    patil  uvw@gmail.com    harry patil
1     ram    pawar  xyz@gmail.com      ram pawar
2   shyam  bhosale  pqr@gmail.com  shyam bhosale
3  pandav   jadhav   abcgmail.com  pandav jadhav

In [17]:
df.rename(columns={'first':'first_name','last':'last_name','full':'full_name'},inplace=True)

In [18]:
df

  first_name last_name          email      full_name
0      harry     patil  uvw@gmail.com    harry patil
1        ram     pawar  xyz@gmail.com      ram pawar
2      shyam   bhosale  pqr@gmail.com  shyam bhosale
3     pandav    jadhav   abcgmail.com  pandav jadhav

In [19]:
df.loc[3]=['Pandav','Jadhav','pandavjadhav@gmail.com','Pandav Jadhav']

In [20]:
df

  first_name last_name                   email      full_name
0      harry     patil           uvw@gmail.com    harry patil
1        ram     pawar           xyz@gmail.com      ram pawar
2      shyam   bhosale           pqr@gmail.com  shyam bhosale
3     Pandav    Jadhav  pandavjadhav@gmail.com  Pandav Jadhav

In [22]:
df.loc[0,['first_name','last_name']]=['Rutwik','Patil']

In [23]:
df

  first_name last_name                   email      full_name
0     Rutwik     Patil           uvw@gmail.com    harry patil
1        ram     pawar           xyz@gmail.com      ram pawar
2      shyam   bhosale           pqr@gmail.com  shyam bhosale
3     Pandav    Jadhav  pandavjadhav@gmail.com  Pandav Jadhav

In [26]:
df.loc[1,'first_name']='Ram'

In [27]:
df

  first_name last_name                   email      full_name
0     Rutwik     Patil           uvw@gmail.com    harry patil
1        Ram     pawar           xyz@gmail.com      ram pawar
2      shyam   bhosale           pqr@gmail.com  shyam bhosale
3     Pandav    Jadhav  pandavjadhav@gmail.com  Pandav Jadhav

In [33]:
df['first_name']=df['first_name'].str.title()

In [34]:
df

  first_name last_name                   email      full_name
0     Rutwik     Patil           uvw@gmail.com    harry patil
1        Ram     pawar           xyz@gmail.com      ram pawar
2      Shyam   bhosale           pqr@gmail.com  shyam bhosale
3     Pandav    Jadhav  pandavjadhav@gmail.com  Pandav Jadhav

In [35]:
df['last_name']=df['last_name'].str.title()

In [36]:
df

  first_name last_name                   email      full_name
0     Rutwik     Patil           uvw@gmail.com    harry patil
1        Ram     Pawar           xyz@gmail.com      ram pawar
2      Shyam   Bhosale           pqr@gmail.com  shyam bhosale
3     Pandav    Jadhav  pandavjadhav@gmail.com  Pandav Jadhav