In [1]:
import pandas as pd

In [2]:
people={
    'first':['harry','ram','shyam','pandav'],
    'last':['patil','pawar','bhosale','jadhav'],
    'email':['uvw@gmail.com','xyz@gmail.com','pqr@gmail.com','abcgmail.com'],
}

In [3]:
df=pd.DataFrame(people)

In [4]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [5]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
df.set_index('first',inplace=True)

In [7]:
df

           last          email
first
harry     patil  uvw@gmail.com
ram       pawar  xyz@gmail.com
shyam   bhosale  pqr@gmail.com
pandav   jadhav   abcgmail.com

In [13]:
df[['last','email']]

           last          email
first
harry     patil  uvw@gmail.com
ram       pawar  xyz@gmail.com
shyam   bhosale  pqr@gmail.com
pandav   jadhav   abcgmail.com

In [15]:
df.index

Index(['harry', 'ram', 'shyam', 'pandav'], dtype='object', name='first')

In [16]:
df.reset_index(inplace=True)

In [17]:
df

    first     last          email
0   harry    patil  uvw@gmail.com
1     ram    pawar  xyz@gmail.com
2   shyam  bhosale  pqr@gmail.com
3  pandav   jadhav   abcgmail.com

In [18]:
df.set_index('first',inplace=True)

In [19]:
df

           last          email
first
harry     patil  uvw@gmail.com
ram       pawar  xyz@gmail.com
shyam   bhosale  pqr@gmail.com
pandav   jadhav   abcgmail.com

In [20]:
df.sort_index(inplace=True)

In [21]:
df

           last          email
first
harry     patil  uvw@gmail.com
pandav   jadhav   abcgmail.com
ram       pawar  xyz@gmail.com
shyam   bhosale  pqr@gmail.com

In [22]:
df.sort_index(ascending=False)

           last          email
first
shyam   bhosale  pqr@gmail.com
ram       pawar  xyz@gmail.com
pandav   jadhav   abcgmail.com
harry     patil  uvw@gmail.com

In [25]:
df.reset_index(inplace=True)

In [26]:
df.sort_index(ascending=False)

    first     last          email
3   shyam  bhosale  pqr@gmail.com
2     ram    pawar  xyz@gmail.com
1  pandav   jadhav   abcgmail.com
0   harry    patil  uvw@gmail.com